name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          APP_NAME="AddaLiveBackend"
          SERVER_HOST="178.128.26.45"

          ssh -o StrictHostKeyChecking=no root@$SERVER_HOST "
            export PATH=/root/.nvm/versions/node/v20.19.5/bin:\$PATH &&  # Use Node path for Yarn
            cd /var/www/$APP_NAME &&
            git stash &&
            git pull origin main &&
            yarn install &&
            yarn build &&
            pm2 delete $APP_NAME > /dev/null 2>&1 || true &&
            echo \"Starting pm2 process: $APP_NAME\" &&
            pm2 start dist/server.js --name $APP_NAME --update-env &&
            pm2 save &&
            echo \"Successfully deployed $APP_NAME with pm2\"
          "
